package lpc

import (
	"math"
	"math/rand/v2"
	"testing"
)

// TestLevinsonRecoversKnownProcess is the test that says the solver is right rather than merely
// plausible: a signal generated by a known recursion must yield those coefficients back.
func TestLevinsonRecoversKnownProcess(t *testing.T) {
	cases := [][]float64{
		{0.5},
		{1.4, -0.6},
		{0.9, -0.3, 0.1},
	}

	for _, want := range cases {
		order := len(want)
		rng := rand.New(rand.NewPCG(3, 7))

		// Drive the recursion with noise so every mode is excited.
		const n = 20000
		x := make([]float64, n)
		for i := range n {
			v := rng.NormFloat64()
			for j := range order {
				if i-1-j >= 0 {
					v += want[j] * x[i-1-j]
				}
			}
			x[i] = v
		}

		autoc := make([]float64, order+1)
		Autocorrelate(x, order, autoc)

		coeffs := make([][]float64, order)
		for i := range coeffs {
			coeffs[i] = make([]float64, order)
		}
		errs := make([]float64, order)

		if got := Levinson(autoc, order, coeffs, errs); got != order {
			t.Fatalf("Levinson stopped at order %d, want %d", got, order)
		}
		for j := range want {
			if math.Abs(coeffs[order-1][j]-want[j]) > 0.05 {
				t.Errorf("order %d: coefficients %v, want %v", order, coeffs[order-1], want)
				break
			}
		}
	}
}

// TestLevinsonErrorFallsWithOrder pins the property an order search relies on.
func TestLevinsonErrorFallsWithOrder(t *testing.T) {
	rng := rand.New(rand.NewPCG(11, 13))
	const n = 4096
	x := make([]float64, n)
	for i := range n {
		x[i] = math.Sin(float64(i)*0.05) * 1000
		x[i] += rng.NormFloat64() * 10
	}

	const maxOrder = 12
	autoc := make([]float64, maxOrder+1)
	Autocorrelate(x, maxOrder, autoc)

	coeffs := make([][]float64, maxOrder)
	for i := range coeffs {
		coeffs[i] = make([]float64, maxOrder)
	}
	errs := make([]float64, maxOrder)

	got := Levinson(autoc, maxOrder, coeffs, errs)
	if got < 2 {
		t.Fatalf("Levinson reached only order %d", got)
	}
	for i := 1; i < got; i++ {
		if errs[i] > errs[i-1]*1.0001 {
			t.Errorf("order %d error %g exceeds order %d error %g", i+1, errs[i], i, errs[i-1])
		}
	}
}

// TestLevinsonHandlesDegenerateInput checks the guards rather than the arithmetic. Silence and
// constants have no prediction to find, and must return an order rather than a NaN.
func TestLevinsonHandlesDegenerateInput(t *testing.T) {
	const maxOrder = 8
	coeffs := make([][]float64, maxOrder)
	for i := range coeffs {
		coeffs[i] = make([]float64, maxOrder)
	}
	errs := make([]float64, maxOrder)

	inputs := map[string][]float64{
		"silence":  make([]float64, 512),
		"constant": constantSlice(512, 1000),
		"impulse":  impulseSlice(512),
	}
	for name, x := range inputs {
		autoc := make([]float64, maxOrder+1)
		Autocorrelate(x, maxOrder, autoc)
		order := Levinson(autoc, maxOrder, coeffs, errs)
		if order < 0 || order > maxOrder {
			t.Errorf("%s: order %d out of range", name, order)
		}
		for i := range order {
			for _, c := range coeffs[i][:i+1] {
				if math.IsNaN(c) || math.IsInf(c, 0) {
					t.Errorf("%s: order %d produced %v", name, i+1, coeffs[i][:i+1])
					break
				}
			}
		}
	}
}

func constantSlice(n int, v float64) []float64 {
	s := make([]float64, n)
	for i := range s {
		s[i] = v
	}
	return s
}

func impulseSlice(n int) []float64 {
	s := make([]float64, n)
	s[0] = 1
	return s
}

func TestAutocorrelate(t *testing.T) {
	x := []float64{1, 2, 3}
	out := make([]float64, 3)
	Autocorrelate(x, 2, out)

	// lag 0: 1+4+9, lag 1: 2*1+3*2, lag 2: 3*1
	want := []float64{14, 8, 3}
	for i := range want {
		if out[i] != want[i] {
			t.Errorf("lag %d = %g, want %g", i, out[i], want[i])
		}
	}
}

func TestTukeyWindow(t *testing.T) {
	w := make([]float64, 100)
	TukeyWindow(w, 0.5)

	if w[0] > 1e-9 {
		t.Errorf("first sample = %g, want ~0", w[0])
	}
	if w[len(w)-1] > 1e-9 {
		t.Errorf("last sample = %g, want ~0", w[len(w)-1])
	}
	if math.Abs(w[50]-1) > 1e-9 {
		t.Errorf("centre = %g, want 1", w[50])
	}
	for i, v := range w {
		if v < -1e-9 || v > 1+1e-9 {
			t.Fatalf("sample %d = %g, outside [0,1]", i, v)
		}
	}

	// A taper of zero is a rectangular window.
	TukeyWindow(w, 0)
	for i, v := range w {
		if v != 1 {
			t.Fatalf("rectangular window sample %d = %g, want 1", i, v)
		}
	}
}

func TestTukeyWindowEmpty(t *testing.T) {
	TukeyWindow(nil, 0.5) // must not panic
}

func BenchmarkAutocorrelate(b *testing.B) {
	x := make([]float64, 4096)
	for i := range x {
		x[i] = math.Sin(float64(i) * 0.01)
	}
	out := make([]float64, 33)
	b.ReportAllocs()
	for b.Loop() {
		Autocorrelate(x, 32, out)
	}
}
